//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int review_id { get; set; }
        public Nullable<int> reviewer_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string review_description { get; set; }
        public Nullable<int> review_rating { get; set; }
    }
}
