//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviewer
    {
        public int reviewer_id { get; set; }
        public string reviewer_last_name { get; set; }
        public string reviewer_first_name { get; set; }
        public string reviewer_email { get; set; }
    }
}
